### ISSUE TITLE
How difficult would it be to parallelise this? 

### ISSUE THREAD

**Issue by apmoore499** [KarolineH/concave_hull#1]
Thank you for this repo! Excellent to see everything organised neatly. 
Is it worth trying to parallelise the code to make it faster?
I'm working on a project atm which needs to run a 3d alphawrap algorithm on a point cloud thousands of times. Currently I am using CGAL / Pymeshlab bindings, and I am able to get something that runs in about a minute, with the drawback that it's only using one core. I can't find a straightforward way to perform the procedure on GPU / with multithread / parallel operations / for the 3D case / do you know if it is possible / easy to do / likely to speed up the calculation drastically? Perhaps replace scipy.spatial.Delaunay with a faster procedure (again, based on misc things I have read online, suggesting scipy Delaunay is relatively slow), or if the goal is too tricky.

**Comment by KarolineH** [comment]
Hi @apmoore499, thanks a lot for your interest in this package. 
I understand your issue and it's true that my implementation here is in no way optimised for computation speed. I'm not actively working on this project at the moment and currently have no plans to add GPU support or parallelisation. 
If you find a solution or end up implementing your own, feel free to submit a pull request or link to your project here.
